spring:
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB


  ldap:
    embedded:
      ldif: classpath:test-server.ldif
      base-dn: dc=springframework,dc=org
      port: 8389